export enum PATCH_SCREEN {
  ONBOARDING = 'ONBOARDING',
  SIGN_IN = 'SIGN_IN',
  FORGOT_PASSWORD = 'FORGOT_PASSWORD',
  OTP_VERIFICATION_FORGOT_PASSWORD = 'OTP_VERIFICATION_FORGOT_PASSWORD',
  RESET_PASSWORD = 'RESET_PASSWORD',
  REGISTER = 'REGISTER',
  OTP_VERIFICATION_REGISTER = 'OTP_VERIFICATION_REGISTER',
  RECOVER_PASSWORD = 'RECOVER_PASSWORD',
  HOME = 'HOME',
  MAIN = 'MAIN',
  HISTORY = 'HISTORY',
}
